nome = input ('Qual é o seu nome? ')
peso = input ('Informe seu peso: ')
dia = input ('Informe o seu dia de Nascimento: ')
mes = input ('Informe o seu mes de Nascimento: ')
ano = input ('Informe o ano do seu Nascumento: ')
print (f'Seu nome é {nome}')
print (f'Seu peso é {peso}')
print (f'Você nasceu no dia {dia} de {mes} de {ano}.')