# CRIE UMA TUPLA PREENCHIDA COM OS 20 PRIMEIROS COLOCADOS DA TABELA DO CAMPEONATO BRASILEIRO DE FUTEBOL, NA ORDEM DE COLOCAÇÃO. DEPOIS MOSTRE:
# A)APENAS OS 5 PRIMEIROS COLOCADOS.
# B)OS ÚLTIMOS COLOCADOS DA TABELA
# C)UMA LISTA COM OS TIMES EM ORDEM.
# D)EM QUE POSIÇÃO NA TABELA ESTÁ O TIME DA CHAPECOENSE. 

