# DESENVOLVA UM PROGRAMA QUE LEIA QUATRO VALORES E GUARDE-OS EM UMA TUPLA. NO FINAL, MOSTRE:
# A) QUANTAS VEZES APARECEU O VALOR 9.
# B) EM QUE POSIÇÃO FOI DIGITADO O PRIMEIRO VALOR 3. 
# C) QUAIS FORAM OS NÚMEROS PARES.